<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\AmiDiskLab.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<RootNamespace>AmiDiskLab.App</RootNamespace>
		<AssemblyName>AmiDiskLab</AssemblyName>
		<Product>AmiDiskLab</Product>
		<Title>AmiDiskLab - Amiga Disk &amp; Software Manager</Title>
		<AssemblyTitle>AmiDiskLab - Amiga Disk &amp; Software Manager</AssemblyTitle>
		<Description>Amiga Disk &amp; Software Manager</Description>
		<Authors>Christoph Schaefer</Authors>
		<Company>Grütze-Software</Company>
		<Copyright>Copyright © 2026 Christoph Schaefer / Grütze-Software</Copyright>
		<Version>1.2</Version>
		<AssemblyVersion>1.2.0.0</AssemblyVersion>
		<FileVersion>1.2.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.8" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RetroDisk.Core\AmiDiskLab.Core.csproj" />
    <ProjectReference Include="..\RetroDisk.Infrastructure\AmiDiskLab.Infrastructure.csproj" />
  </ItemGroup>
</Project>
